import type { MilitaryBranch } from './types';

export const ranksByBranch: Record<MilitaryBranch, string[]> = {
  'Army': [
    'Private (PVT)',
    'Private First Class (PFC)',
    'Specialist (SPC)',
    'Corporal (CPL)',
    'Sergeant (SGT)',
    'Staff Sergeant (SSG)',
    'Sergeant First Class (SFC)',
    'Master Sergeant (MSG)',
    'First Sergeant (1SG)',
    'Master Sergeant First Class (MSFPC)',
    'Sergeant Major (SGM)',
    'Command Sergeant Major (CSM)',
    'Warrant Officer (WO1)',
    'Chief Warrant Officer (CW2)',
    'Chief Warrant Officer (CW3)',
    'Chief Warrant Officer (CW4)',
    'Chief Warrant Officer (CW5)',
    'Second Lieutenant (2LT)',
    'First Lieutenant (1LT)',
    'Captain (CPT)',
    'Major (MAJ)',
    'Lieutenant Colonel (LTC)',
    'Colonel (COL)',
    'Brigadier General (BG)',
    'Major General (MG)',
    'Lieutenant General (LTG)',
    'General (GEN)',
  ],
  'Navy': [
    'Seaman Recruit (SR)',
    'Seaman Apprentice (SA)',
    'Seaman (SN)',
    'Petty Officer Third Class (PO3)',
    'Petty Officer Second Class (PO2)',
    'Petty Officer First Class (PO1)',
    'Chief Petty Officer (CPO)',
    'Senior Chief Petty Officer (SCPO)',
    'Master Chief Petty Officer (MCPO)',
    'Master Chief Petty Officer of the Navy (MCPON)',
    'Warrant Officer (WO)',
    'Chief Warrant Officer (CWO2)',
    'Chief Warrant Officer (CWO3)',
    'Chief Warrant Officer (CWO4)',
    'Ensign (ENS)',
    'Lieutenant Junior Grade (LTJG)',
    'Lieutenant (LT)',
    'Lieutenant Commander (LCDR)',
    'Commander (CDR)',
    'Captain (CAPT)',
    'Rear Admiral Lower Half (RADM)',
    'Rear Admiral (RADM)',
    'Vice Admiral (VADM)',
    'Admiral (ADM)',
  ],
  'Air Force': [
    'Airman Basic (AB)',
    'Airman (AMN)',
    'Airman First Class (A1C)',
    'Senior Airman (SrA)',
    'Staff Sergeant (SSgt)',
    'Technical Sergeant (TSgt)',
    'Master Sergeant (MSgt)',
    'Senior Master Sergeant (SMSgt)',
    'Chief Master Sergeant (CMSgt)',
    'Chief Master Sergeant of the Air Force (CMSAF)',
    'Warrant Officer (WO)',
    'Chief Warrant Officer (CWO2)',
    'Chief Warrant Officer (CWO3)',
    'Chief Warrant Officer (CWO4)',
    'Chief Warrant Officer (CWO5)',
    'Second Lieutenant (2d Lt)',
    'First Lieutenant (1st Lt)',
    'Captain (Capt)',
    'Major (Maj)',
    'Lieutenant Colonel (Lt Col)',
    'Colonel (Col)',
    'Brigadier General (Brig Gen)',
    'Major General (Maj Gen)',
    'Lieutenant General (Lt Gen)',
    'General (Gen)',
  ],
  'Marine Corps': [
    'Private (Pvt)',
    'Private First Class (PFC)',
    'Lance Corporal (LCpl)',
    'Corporal (Cpl)',
    'Sergeant (Sgt)',
    'Staff Sergeant (SSgt)',
    'Gunnery Sergeant (GySgt)',
    'Master Sergeant (MSgt)',
    'First Sergeant (1stSgt)',
    'Master Gunnery Sergeant (MGySgt)',
    'Master Sergeant Major (MSgtMajor)',
    'Sergeant Major (SgtMajor)',
    'Sergeant Major of the Marine Corps (SgtMajMC)',
    'Warrant Officer (WO)',
    'Chief Warrant Officer (CWO2)',
    'Chief Warrant Officer (CWO3)',
    'Chief Warrant Officer (CWO4)',
    'Chief Warrant Officer (CWO5)',
    'Second Lieutenant (2ndLt)',
    'First Lieutenant (1stLt)',
    'Captain (Capt)',
    'Major (Maj)',
    'Lieutenant Colonel (LtCol)',
    'Colonel (Col)',
    'Brigadier General (BGen)',
    'Major General (MajGen)',
    'Lieutenant General (LtGen)',
    'General (Gen)',
  ],
  'Coast Guard': [
    'Seaman Recruit (SR)',
    'Seaman Apprentice (SA)',
    'Seaman (SN)',
    'Petty Officer Third Class (PO3)',
    'Petty Officer Second Class (PO2)',
    'Petty Officer First Class (PO1)',
    'Chief Petty Officer (CPO)',
    'Senior Chief Petty Officer (SCPO)',
    'Master Chief Petty Officer (MCPO)',
    'Master Chief Petty Officer of the Coast Guard (MCPOCG)',
    'Warrant Officer (WO)',
    'Chief Warrant Officer (CWO2)',
    'Chief Warrant Officer (CWO3)',
    'Chief Warrant Officer (CWO4)',
    'Ensign (ENS)',
    'Lieutenant Junior Grade (LTJG)',
    'Lieutenant (LT)',
    'Lieutenant Commander (LCDR)',
    'Commander (CDR)',
    'Captain (CAPT)',
    'Rear Admiral Lower Half (RADM)',
    'Rear Admiral (RADM)',
    'Vice Admiral (VADM)',
    'Admiral (ADM)',
  ],
  'Space Force': [
    'Specialist (Spc)',
    'Airman (Amn)',
    'Airman First Class (A1C)',
    'Senior Airman (SrA)',
    'Staff Sergeant (SSgt)',
    'Technical Sergeant (TSgt)',
    'Master Sergeant (MSgt)',
    'Senior Master Sergeant (SMSgt)',
    'Chief Master Sergeant (CMSgt)',
    'Chief Master Sergeant of the Space Force (CMSSF)',
    'Warrant Officer (WO)',
    'Chief Warrant Officer (CWO2)',
    'Chief Warrant Officer (CWO3)',
    'Chief Warrant Officer (CWO4)',
    'Chief Warrant Officer (CWO5)',
    'Second Lieutenant (2d Lt)',
    'First Lieutenant (1st Lt)',
    'Captain (Capt)',
    'Major (Maj)',
    'Lieutenant Colonel (Lt Col)',
    'Colonel (Col)',
    'Brigadier General (Brig Gen)',
    'Major General (Maj Gen)',
    'Lieutenant General (Lt Gen)',
    'General (Gen)',
  ],
};
